<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace Go2Flow\SaasRegisterLogin\Models\Relations\AbstractModels;

use Illuminate\Database\Eloquent\Relations\Pivot;

/**
* Class AbstractTeamUser
* @package Go2Flow\SaasRegisterLogin\Models\Relations\AbstractModels
*
* @property bigInteger $user_id
* @property bigInteger $team_id
*/ 
abstract class AbstractTeamUser extends Pivot
{
    /**  
     * Primary key name.
     * 
     * @var string
     */
    public $primaryKey = 'user_id';
    
    /**  
     * Primary key is non-autoincrementing.
     * 
     * @var bool
     */
    public $incrementing = false;
    
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'user_id' => 'integer',
        'team_id' => 'integer'
    ];
}
