<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: ae0a6723-8cde-4d91-80eb-04527cec60ce
 * Migration local datetime: 2022-11-17 10:35:43.974731
 * Migration UTC datetime: 2022-11-17 09:35:43.974731
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations2022111710354397 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('teams', function (Blueprint $table) {
            $table->boolean('checklist_completed')->nullable(true)->default(0)->after('bank_swift');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('teams', function (Blueprint $table) {
            $table->dropColumn('checklist_completed');
        });
    }
}
