<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: 726ccc49-9827-4f19-b413-91dd33ab983c
 * Migration local datetime: 2022-04-06 16:17:51.544348
 * Migration UTC datetime: 2022-04-06 14:17:51.544348
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations2022040616175154 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('teams', function (Blueprint $table) {
            $table->json('receipt_emails')->nullable(true)->after('billing_country')->change();
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('teams', function (Blueprint $table) {
            $table->json('receipt_emails')->nullable(true)->after('billing_country')->change();
        });
    }
}
