<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: 033edce1-58ce-4a98-b283-96933493f4a3
 * Migration local datetime: 2022-03-28 16:00:12.357101
 * Migration UTC datetime: 2022-03-28 14:00:12.357101
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations2022032816001235 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
    }
}
