<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: 93e06c71-3bc5-47e1-a2be-e1480f201715
 * Migration local datetime: 2022-04-05 12:40:11.085316
 * Migration UTC datetime: 2022-04-05 10:40:11.085316
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations01SaasRegisterLogin2022040512401108 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->bigInteger('referral_id')->nullable(true)->unsigned();
            $table->string('salutation', 10)->nullable(true);
            $table->string('firstname', 255);
            $table->string('lastname', 255);
            $table->string('email', 255);
            $table->timestamp('email_verified_at')->nullable(true);
            $table->string('password', 255);
            $table->string('remember_token', 100)->nullable(true);
            $table->timestamp('terms_accepted_at')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->timestamp('deleted_at')->nullable(true);
            $table->unique(['email'], 'users_email_unique');
        });
        Schema::create('teams', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('psp_id', 64)->unique();
            $table->bigInteger('owner_id')->nullable(true)->unsigned();
            $table->string('name', 255);
            $table->string('email', 255);
            $table->string('currency', 3);
            $table->json('languages');
            $table->string('extra_billing_information', 255)->nullable(true);
            $table->string('billing_address', 255);
            $table->string('billing_address_line_2', 255)->nullable(true);
            $table->string('billing_city', 255);
            $table->string('billing_state')->nullable(true);
            $table->string('billing_postal_code', 25);
            $table->string('billing_country', 2);
            $table->string('receipt_emails', 255)->nullable(true);
            $table->string('vat_id', 50)->nullable(true);
            $table->string('tax_number', 255)->nullable(true);
            $table->string('bank_name')->nullable(true);
            $table->string('bank_iban')->nullable(true);
            $table->string('bank_swift')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->timestamp('deleted_at')->nullable(true);
        });
        Schema::create('team_user', function (Blueprint $table) {
            $table->bigInteger('user_id')->unsigned();
            $table->bigInteger('team_id')->unsigned();
            $table->primary(['user_id','team_id']);
        });
        Schema::create('referrals', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->json('name');
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('layouts', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('name')->nullable(true);
            $table->string('version')->nullable(true);
            $table->string('url')->nullable(true);
            $table->boolean('available')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
        });
        Schema::create('team_layouts', function (Blueprint $table) {
            $table->bigInteger('team_id')->unsigned();
            $table->bigInteger('layouts_id')->unsigned();
            $table->longText('custom_css')->nullable(true);
            $table->string('primary_color')->nullable(true);
            $table->string('secondary_color')->nullable(true);
            $table->primary(['team_id','layouts_id']);
        });
        Schema::table('users', function (Blueprint $table) {
            $table->foreign('referral_id')->references('id')->on('referrals');
        });
        Schema::table('teams', function (Blueprint $table) {
            $table->foreign('owner_id')->references('id')->on('users');
        });
        Schema::table('team_user', function (Blueprint $table) {
            $table->foreign('user_id')->references('id')->on('users');
            $table->foreign('team_id')->references('id')->on('teams');
        });
        Schema::table('team_layouts', function (Blueprint $table) {
            $table->foreign('team_id')->references('id')->on('teams');
            $table->foreign('layouts_id')->references('id')->on('layouts');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('team_layouts', function (Blueprint $table) {
            $table->dropForeign(['team_id']);
            $table->dropForeign(['layouts_id']);
        });
        Schema::table('team_user', function (Blueprint $table) {
            $table->dropForeign(['user_id']);
            $table->dropForeign(['team_id']);
        });
        if (Schema::hasTable('teams')) {
            Schema::table('teams', function (Blueprint $table) {
                $table->dropForeign(['owner_id']);
            });
        }
        if (Schema::hasTable('users')) {
            Schema::table('users', function (Blueprint $table) {
                $table->dropForeign(['referral_id']);
            });
        }
        Schema::dropIfExists('team_layouts');
        Schema::dropIfExists('layouts');
        Schema::dropIfExists('referrals');
        Schema::dropIfExists('team_user');
        Schema::dropIfExists('teams');
        Schema::dropIfExists('users');
    }
}
