<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace Go2Flow\SaasRegisterLogin\Models\Team\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractInvitation
* @package Go2Flow\SaasRegisterLogin\Models\Team\AbstractModels
*
* @property bigInteger $id
* @property string $email
* @property bigInteger $role_id
* @property bigInteger $team_id
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property \Go2Flow\SaasRegisterLogin\Models\Team|null $team
*/ 
abstract class AbstractInvitation extends Model
{
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'email' => 'string',
        'role_id' => 'integer',
        'team_id' => 'integer',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
    
    public function team()
    {
        return $this->belongsTo('\Go2Flow\SaasRegisterLogin\Models\Team', 'team_id', 'id');
    }
}
