<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace Go2Flow\SaasRegisterLogin\Models\AbstractModels;

use Illuminate\Database\Eloquent\Relations\Pivot;

/**
* Class AbstractTeamLayouts
* @package Go2Flow\SaasRegisterLogin\Models\AbstractModels
*
* @property bigInteger $team_id
* @property bigInteger $layouts_id
* @property longText $custom_css
* @property string $primary_color
* @property string $secondary_color
*/ 
abstract class AbstractTeamLayouts extends Pivot
{
    /**  
     * Primary key name.
     * 
     * @var string
     */
    public $primaryKey = 'team_id';
    
    /**  
     * Primary key is non-autoincrementing.
     * 
     * @var bool
     */
    public $incrementing = false;
    
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'team_id' => 'integer',
        'layouts_id' => 'integer',
        'custom_css' => 'string',
        'primary_color' => 'string',
        'secondary_color' => 'string'
    ];
    
    /**  
     * The attributes that are mass assignable.
     * 
     * @var array
     */
    protected $fillable = [
        'team_id',
        'layouts_id',
        'custom_css',
        'primary_color',
        'secondary_color'
    ];
}
