<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace Go2Flow\SaasRegisterLogin\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractReferral
* @package Go2Flow\SaasRegisterLogin\Models\AbstractModels
*
* @property bigInteger $id
* @property json $name
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property \Illuminate\Database\Eloquent\Collection $users
*/ 
abstract class AbstractReferral extends Model
{
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'array',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
    
    public function users()
    {
        return $this->hasMany('\Go2Flow\SaasRegisterLogin\Models\User', 'referral_id', 'id');
    }
}
