<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace Go2Flow\SaasRegisterLogin\Models\AbstractModels;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
* Class AbstractUser
* @package Go2Flow\SaasRegisterLogin\Models\AbstractModels
*
* @property bigInteger $id
* @property string $salutation
* @property string $firstname
* @property string $lastname
* @property string $email
* @property \Carbon\Carbon $email_verified_at
* @property string $password
* @property string $remember_token
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property \Carbon\Carbon $deleted_at
* @property \Illuminate\Database\Eloquent\Collection $owned_teams
* @property \Illuminate\Database\Eloquent\Collection $created_courses
* @property \Illuminate\Database\Eloquent\Collection $courses
*/ 
abstract class AbstractUser extends \Illuminate\Foundation\Auth\User
{
    use SoftDeletes;
    
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'users';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'salutation' => 'string',
        'firstname' => 'string',
        'lastname' => 'string',
        'email' => 'string',
        'email_verified_at' => 'datetime',
        'password' => 'string',
        'remember_token' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime'
    ];
    
    /**  
     * The attributes that should be mutated to dates.
     * 
     * @var array
     */
    protected $dates = ['deleted_at'];
    
    public function owned_teams()
    {
        return $this->hasMany('\Go2Flow\SaasRegisterLogin\Models\Team', 'owner_id', 'id');
    }
    
    public function created_courses()
    {
        return $this->hasMany('\App\Models\Course\Course', 'user_id', 'id');
    }
    
    public function courses()
    {
        return $this->hasMany('\App\Models\Course\Course', 'instructor_id', 'id');
    }
    
    public function teams()
    {
        return $this->belongsToMany('\Go2Flow\SaasRegisterLogin\Models\Team', 'team_user', 'user_id', 'team_id');
    }
}
