<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace Go2Flow\SaasRegisterLogin\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractLayouts
* @package Go2Flow\SaasRegisterLogin\Models\AbstractModels
*
* @property bigInteger $id
* @property string $name
* @property string $version
* @property string $url
* @property boolean $available
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
*/ 
abstract class AbstractLayouts extends Model
{
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'version' => 'string',
        'url' => 'string',
        'available' => 'boolean',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
    
    /**  
     * The attributes that are mass assignable.
     * 
     * @var array
     */
    protected $fillable = [
        'id',
        'name',
        'version',
        'url',
        'available',
        'created_at',
        'updated_at'
    ];
    
    public function teams()
    {
        return $this->belongsToMany('\Go2Flow\SaasRegisterLogin\Models\Team', 'team_layouts', 'layouts_id', 'team_id')->withPivot('custom_css', 'primary_color', 'secondary_color');
    }
}
